### ISSUE TITLE
Do you have something like this for a tornado/mongo app?

### ISSUE THREAD

**Issue by pfortin-urbn** [lightstep/python-opentelemetry-walkthrough#1]
I loved this example - I am wondering how it would differ if this was a tornado / mongo micro service - as well how does it work if one micro-service calls another inside 1 request does it trace across services / DBs?

**Comment by ocelotl** [comment]
Hello @pfortin-urbn!

Please excuse my late reply. I don't have an answer right now, will have to investigate.

I'm assigning myself this issue right now.

Thanks!

**Comment by ocelotl** [comment]
Hello again, @pfortin-urbn 

We still don't have for Tornado or Mongo instrumentation. We can add an example in the future when we have all the components ready.

Thanks!

**Comment by kayousterhout** [comment]
closing this issue in anticipation of archiving this repository (more up to date example are at https://github.com/lightstep/opentelemetry-examples)
